name: Flutter Web to GitHub Pages

on:
  push:
    branches:
      - test/testowy
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version | cat

      - name: Enable web
        run: flutter config --enable-web | cat

      - name: Ensure web platform files
        run: flutter create . --platforms=web | cat

      - name: Install dependencies
        run: flutter pub get | cat

      - name: Build web
        run: flutter build web --release --base-href /Pierwsze-sobotyv2/ | cat

      - name: Show build output
        run: ls -la build/web | cat

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build/web
          force_orphan: true